services:
  attendance-api: 
    image: kucingemas/go-attendance-api:latest
    container_name: attendance-api
    restart: always
    env_file:
      - .env
    ports: 
      - "127.0.0.1:8002:8002"
    volumes:
      - ./.env:/app/.env
    networks:
      - shared-networks

networks:
  shared-networks:
    name: shared-networks
    external: true
