include .env
export

.PHONY: up down restart logs pull clean

up:
	docker compose -f docker-compose.vps.yaml up -d

down:
	docker compose -f docker-compose.vps.yaml down

restart:
	docker compose -f docker-compose.vps.yaml restart

logs:
	docker compose -f docker-compose.vps.yaml logs -f app

pull:
	docker compose -f docker-compose.vps.yaml pull

clean:
	docker image prune -f
