basePath: /
definitions:
  model.AttendanceRequest:
    properties:
      action:
        type: string
      employee_id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
    required:
    - action
    - employee_id
    - latitude
    - longitude
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  description: API documentation for HRD Attendance System
  title: HRD Attendance API
  version: "1.0"
paths:
  /api/v1/attendance:
    post:
      consumes:
      - application/json
      description: Endpoint to record employee clock-in and clock-out with geolocation
      parameters:
      - description: 'Attendance Data (Action: clock_in/clock_out)'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AttendanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Record Attendance
      tags:
      - Attendance
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login employee
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register new employee
      tags:
      - Auth
  /api/v1/ping:
    get:
      description: Endpoint to check API status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - Health
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: Get list of users with dynamic filter and sorting
      parameters:
      - description: Filter by Name
        in: query
        name: name
        type: string
      - description: Filter by Email
        in: query
        name: email
        type: string
      - description: Order by field (e.g., name, created_at)
        in: query
        name: order_by
        type: string
      - description: Sort direction (asc or desc)
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get All Users
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
